#!/bin/bash

vms=( 7 6 5 4 3 2 1 )

run=1
infile=8vms-r$run.mig
outfile=migtime

cmd="grep \"total time\" $infile | awk '{print \$3}'"

#"$cmd" > $outfile
echo -n "8 " > $outfile
grep "total time" $infile | awk '{print $3}' | tr '\n' ' ' >> $outfile
echo >> $outfile

for vm in ${vms[@]}
do
	infile=${vm}vms-r$run.mig
	echo -n "$vm " >> $outfile
	#"$cmd" >> $outfile
	grep "total time" $infile | awk '{print $3}' | tr '\n' ' ' >> $outfile
	echo >> $outfile
done

echo $outfile generated.
