#!/bin/bash

#============ for loop test ============
echo "============ for loop test ============"
vms=5
for ((  i = 0 ;  i <= $vms;  i++  ))
do
  echo "Welcome $i times"
done
echo ""

# doesn't work with the following two variables
#for i in {1..${vms}}
#for i in {1..$vms}
for i in {1..5}
do
   echo "Welcome $i times"
done
echo ""

echo "============ Nested for loop with arrays test ============"
odds=(1 3 5)
evens=(2 4 6)
for odd in ${odds[@]}
do 
	for even in ${evens[@]}
	do 
		echo -n "$odd $even "
	done
	echo ""
done
echo ""

echo "============ Nested for loop test ============"
for (( i = 1; i <= $vms; i++ ))      ### Outer for loop ###
do

    for (( j = 1 ; j <= 5; j++ )) ### Inner for loop ###
    do
          echo -n "$i "
    done

  echo "" #### print the new line ###

done
echo ""

#============ arithmetic expression test ============
echo "============ arithmetic expression test ============"
comp=`expr 0.5 "<" 1`
echo $comp
#if [ 0.5 -lt 1 ]; then
if [ $comp -eq 1 ]; then
	echo "yes 0.5 < 1"
else
	echo "no 0.5 >= 1"
fi
