#!/bin/bash

# parse throughput density from dstat files

#infile=$1
prefix=${infile%.*}
run=1

windows=( 1 2 4 6 8 10 12 14 16 18 20 40 )
#windows=( 1 2 4 6 7 8 9 10 )

basedir=/root/miglog/plot

outfile=density
#outfile=$prefix.density

for window in ${windows[@]}
do
	infile=${window}vms-r${run}.dstat
	densfile=${window}vms-r${run}.density
	thruputfile=${window}vms.throughput

	# parse density of MByte throughputs from dstat file
	# remove outlier greater than 120MB/s
#	awk '{print $2}' $infile | grep M | cut -d "|" -f 1 | cut -d "M" -f 1 | awk '$N <= 120' > $densfile

	# parse density of MByte throughputs from dstat file
	# remove outlier greater than 120MB/s
#	awk '{print $2}' $infile | grep k | cut -d "|" -f 1 | cut -d "k" -f 1 | awk '{print $1/1000}' | awk '$N <= 120' >> $densfile

	$basedir/plotdensity.R $thruputfile

	pastestr="$pastestr $densfile"
done

#paste $pastestr > $outfile

#echo $outfile generated.

#$basedir/plotdensityall.R $outfile

