#!/bin/bash

infile=$1
basedir=/root/miglog/plot

outfile=$infile.density

# parse density over 1M throughput from dstat file
awk '{print $2}' $infile | cut -d "|" -f 1 | grep M | cut -d "M" -f 1 > $outfile
#awk '{print $2}' 2vms-r1.dstat | cut -d "|" -f 1 | grep M

echo $outfile generated.

$basedir/plotdensity.R $outfile

