#!/bin/bash

infile=$1
basedir=/root/miglog/plot

outfile=$infile.density

# parse density from dstat file
awk '{print $2}' $infile | cut -d "|" -f 1 | grep M > $densfile
#awk '{print $2}' 2vms-r1.dstat | cut -d "|" -f 1 | grep M

echo $outfile generated.

$basedir/plotdensity.R $densfile

