#!/bin/bash

basedir=/home/tsugawa/vmanage

prefix=$HOSTNAME

if [ $# -lt 1 ]; then
        echo usage: $0 cwnd
        exit
fi

# number of concurrent connections
cwnd=$1

from=1
to=40

# sleep time
#interval=1
interval=0.1

#if [ $# == 1 ]
#then
        rvms=`virsh list | grep running | grep $prefix- | wc -l`

#       sleep $((RANDOM%100))

#       while [ $rvms -ne 0 ]
        for (( i = $from ; i <= $to ; i++ ))
        do
                # vms in migration
                vms=`ps -ef | grep migrate | grep $prefix- | wc -l`

                if [ $vms -lt $cwnd ]; then
                #       echo "./migrate $vm &"
                        #vm=`virsh list | grep running | awk '{print $2}' | grep $prefix- | head -1`
                        vm=$prefix-$i
	                echo rvms $rvms vms $vms $vm
                        time -p $basedir/migrate $vm &
                else
                        i=$((-- i))
                fi

               sleep $interval

                rvms=`virsh list | grep running | grep $prefix- | wc -l`

        done
        wait

