#!/bin/bash

# migrate vms in parallel
basedir=/home/tsugawa
vmanage=$basedir/vmanage

exec=parallel

#vms=$1
sampletime=$1
round=$2
title=${vms}vms-r${round}

webdir=1-1/parallel
logdir=$basedir/log/$webdir
log=$logdir/$title.log
dstat=$logdir/$title.dstat

genplot=$basedir/log/plot/genplot

dest=f31
if [ $HOSTNAME == "pm11" ]; then
       dest=f32
elif [ $HOSTNAME == "pm10" ]; then
       dest=f31
elif [ $HOSTNAME == "c11node10" ]; then
       dest=c11node9
fi

mkdir -p $logdir

dstat -nc -N eth0 --nocolor --noheaders > $dstat &

logsave $log time -p $vmanage/$exec $vms &
logsave $log2 time -p $vmanage/$exec2 $vms

sleep 3

pgrep -fl dstat| awk '{print $1}' | xargs kill -9

$genplot $log $webdir

ssh $dest /root/migration/vmanage/destroy

sleep 60

$vmanage/startall 40

