#!/bin/bash

# another hosts to run this code
#hosts=( pm10 )
hosts=( )

expname=sampletime
#expname=basic

homedir=/home/tsugawa
basedir=$homedir/exp
exppath=$basedir/$expname

# sleep time in seconds
sleep_time=1800

#sleep 1800

#runs=( 1 )
runs=( 11 )
#runs=( 1 2 3 4 5 6 7 8 9 10 )

#sampletimes=( 30 )
#sampletimes=( 5 10 )
sampletimes=( 20 30 45 60 90 120 )
#sampletimes=( 5 10 20 30 45 60 90 120 )

for run in ${runs[@]}
do
	for sampletime in ${sampletimes[@]}
	do
		cmd="$exppath $sampletime"

		#echo $cmd r$run $(( run + 1 ))
	        $cmd $run

         	sleep $sleep_time
	done
done

# plot all with statistics
# vms total_migration_time avg_indiv_time variance stdev
#genplotall=$homedir/log/plot/gendataall
#$genplotall

